const PmsLang = window['PmsPcCenterLang'] || {};

const targetConfig = {
  cannotfindnode: ['pms_cannotfindnode', '未找到该树节点'],
  zwxyqrdrz: ['pms_zwxyqrdrz', '暂无需要确认的日志'],
  zwxybhdrz: ['pms_zwxybhdrz', '暂无需要驳回的日志'],
  dp: ['pms_dp', '点评'],
  zzsc: ['pms_zzsc', '正在上传'],
  sqyfc: ['pms_sqyfc', '申请已发出'],
  sfqrsqch: ['pms_sfqrsqch', '是否确认申请撤回'],
  drz: ['pms_drz', '的日志'],
  xmxs: ['pms_xmxs', '项目下属'],
  qxxzry: ['pms_qxxzry', '请先选择人员'],
  qrhbh: ['pms_qrhbh', '确认或驳回'],
  zqrhbh: ['pms_zqrhbh', '周确认或驳回'],
  yqrhbh: ['pms_yqrhbh', '月确认或驳回'],
  xmry: ['pms_xmry', '项目人员'],
  zznqtcy: ['pms_zznqtcy', '组织内其他成员'],
  xmyx: ['pms_xmyx', '项目邮箱'],
  khry: ['pms_khry', '客户人员'],
  qt: ['pms_qt', '其他'],
  fs: ['pms_fs', '发送'],
  zwsj: ['pms_zwsj', '暂无数据'],
  wdrz: ['pms_wdrz', '我的日志'],
  wdxmrz: ['pms_wdxmrz', '我的项目日志'],
  tdxmrz: ['pms_tdxmrz', '团队项目日志'],
  xmrz: ['pms_xmrz', '项目日志'],
  grrz: ['pms_grrz', '个人日志'],
  xsrz: ['pms_xsrz', '下属日志'],
  wdrc: ['pms_wdrc', '我的日程'],
  tdxmrc: ['pms_tdxmrc', '团队项目日程'],
  xmrc: ['pms_xmrc', '项目日程'],
  xsrc: ['pms_xsrc', '下属日程'],
  xztdcy: ['pms_xztdcy', '选择团队成员'],
  tdcy: ['pms_tdcy', '团队成员'],
  qxxzxm: ['pms_qxxzxm', '请先选择项目'],
  hdjt: ['pms_hdjt', '回到今天'],
  month: ['pms_month', '月'],
  week: ['pms_week', '周'],
  day: ['pms_day', '天'],
  hour: ['pms_hour', '小时'],
  allday: ['pms_allday', '全天'],
  more: ['pms_more', '更多'],
  sxqd: ['pms_sxqd', '事项清单'],
  wsb: ['pms_wsb', '未上报'],
  ysb: ['pms_ysb', '已上报'],
  ybh: ['pms_ybh', '已驳回'],
  yqr: ['pms_yqr', '已确认'],
  xs: ['pms_xs', '下属'],
  qxz: ['pms_qxz', '请选择'],
  bc: ['pms_bc', '保存'],
  sc: ['pms_sc', '删除'],
  sb: ['pms_sb', '上报'],
  dqzmyysbdrz: ['pms_dqzmyysbdrz', '当前周没有已上报的日志'],
  dqymyysbdrz: ['pms_dqymyysbdrz', '当前月没有已上报的日志'],
  qxqddqzq: ['pms_qxqddqzq', '请先确定当前周期'],
  wxzrq: ['pms_wxzrq', '未选择日期'],
  dqxzrqmyysbdrz: ['pms_dqxzrqmyysbdrz', '当前选择日期没有已上报的日志'],
  dqxzrqmywsbdrz: ['pms_dqxzrqmywsbdrz', '当前选择日期没有未上报的日志'],
  sbrzgsbxdyl: ['pms_sbrzgsbxdyl', '上报日志工时必须大于0'],
  rzsb: ['pbs_rzsb', '日志上报'],
  bcbsb: ['pms_bcbsb', '保存并上报'],
  sqch: ['pms_sqch', '申请撤回'],
  yfs: ['pms_yfs', '已发送'],
  qr: ['pms_qr', '确认'],
  qx: ['pms_qx', '取消'],
  bh: ['pms_bh', '驳回'],
  gb: ['pms_gb', '关闭'],
  qsr: ['pms_qsr', '请输入'],
  sj: ['pms_sj', '时间'],
  kssj: ['pms_kssj', '开始时间'],
  z: ['pms_z', '至'],
  jssj: ['pms_jssj', '结束时间'],
  rq: ['pms_rq', '日期'],
  xzrq: ['pms_xzrq', '选择日期'],
  lx: ['pms_lx', '类型'],
  gsh: ['pms_gsh', '工时(h)'],
  ztgsh: ['pms_ztgsh', '在途工时(h)'],
  yxgsh: ['pms_yxgsh', '有效工时(h)'],
  xm: ['pms_xm', '项目'],
  tx: ['pms_tx', '提醒'],
  btx: ['pms_btx', '不提醒'],
  sstx: ['pms_sstx', '实时提醒'],
  fzq15: ['pms_fzq15', '15分钟前'],
  fzq30: ['pms_fzq30', '30分钟前'],
  xsq1: ['pms_xsq1', '1小时前'],
  xsq3: ['pms_xsq3', '3小时前'],
  tq1: ['pms_tq1', '1天前'],
  bm: ['pms_bm', '保密'],
  bm1: ['pms_bm1', '保密(项目经理以外人员)'],
  mk: ['pms_mk', '模块'],
  wbsmk: ['pms_wbsmk', 'WBS模块'],
  sjld: ['pms_sjld', '上级领导'],
  cs: ['pms_cs', '抄送'],
  rznr: ['pms_rznr', '日志内容'],
  rcnr: ['pms_rcnr', '日程内容'],
  hy: ['pms_hy', '会议'],
  lcjs: ['pms_lcjs', '撞单检索'],
  sjlb: ['pms_sjlb', '商机列表'],
  sjdj: ['pms_sjdj', '商机登记'],
  rygl: ['pms_rygl', '人员管理'],
  wdnh: ['pms_wdnh', '文档内核'],
  srmcjs: ['pms_srmcjs', '输入名称检索'],
  inputEmail: ['pms_inputemail', '直接输入Email地址，多个Email之间用逗号分隔'],
  qxzfsdx: ['pms_qxzfsdx', '请先选择发送对象'],
  sending: ['pms_sending', '正在发送'],
  qxzsbldhcsry: ['pms_qxzsbldhcsry', '请先选择上报领导或者抄送人员'],
  qlxglyzqxzxjxsq: ['pms_qlxglyzqxzxjxsq', '请联系管理员在权限中心进行授权'],
  all: ['pms_all', '全部'],
  auditing: ['pms_auditing', '审批中'],
  author: ['pms_author', '作者'],
  basemessage: ['pms_basemessage', '基本信息'],
  contract: ['pms_contract', '合同'],
  contractno: ['pms_contractno', '合同号'],
  contractmeney: ['pms_contractmeney', '合同款'],
  receivemeney: ['pms_receivemeney', '已收款'],
  payAmount: ['pms_payAmount', '已付款'],
  copy: ['pms_copy', '复制'],
  createdate: ['pms_createdate', '创建日期'],
  custom: ['pms_custom', '客户'],
  delete: ['pms_delete', '删除'],
  dfdsr: ['pms_dfdsr', '对方当事人'],
  doc: ['pms_doc', '文档'],
  doccatalog: ['pms_doccatalog', '目录'],
  doccreator: ['pms_doccreator', '创建者'],
  doceditdate: ['pms_doceditdate', '修改日期'],
  doclib: ['pms_doclib', '文档类别'],
  doclibcatalog: ['pms_doclibcatalog', '文档类别目录'],
  qtxmlm: ['pms_qtxmlm', '请填写目录名称'],
  docmy: ['pms_docmy', '我的文档'],
  docname: ['pms_docname', '文件名'],
  docnum: ['pms_docnum', '文档编码'],
  docupload: ['pms_docupload', '上传文档'],
  download: ['pms_download', '下载'],
  edit: ['pms_edit', '修改'],
  editdoc: ['pms_editdoc', '修改文档'],
  historyversion: ['pms_historyversion', '历史版本'],
  jwjfzd: ['pms_jwjfzd', '将文件复制到'],
  jwjydz: ['pms_jwjydz', '将文件移动到'],
  kpxx: ['pms_kpxx', '发票信息'],
  log: ['pms_log', '日志'],
  move: ['pms_move', '移动'],
  newdir: ['pms_newdir', '新建目录'],
  ongoing: ['pms_ongoing', '进行中'],
  pluploaddoc: ['pms_pluploaddoc', '批量上传文档'],
  prodate: ['pms_prodate', '项目日期'],
  prodfdsr: ['pms_prodfdsr', '对方当事人'],
  project: ['pms_project', '项目'],
  promanager: ['pms_promanager', '项目经理'],
  proname: ['pms_proname', '项目名称'],
  pronum: ['pms_pronum', '项目号'],
  prostatus: ['pms_prostatus', '项目状态'],
  protype: ['pms_protype', '项目类型'],
  proywy: ['pms_proywy', '业务员'],
  query: ['pms_query', '查询'],
  reset: ['pms_reset', '重置'],
  schedule: ['pms_schedule', '日程'],
  search: ['pms_search', '搜索'],
  security: ['pms_security', '密级'],
  selecttemplate: ['pms_selecttemplate', '请选择模板文件'],
  skxx: ['pms_skxx', '收款信息'],
  fkxx: ['pms_fkxx', '付款信息'],
  templatedownload: ['pms_templatedownload', '模板下载'],
  version: ['pms_version', '版本'],
  xgf: ['pms_xgf', '相关方'],
  yysq: ['pms_yysq', '用印申请'],
  batchcompressor: ['pms_batchcompressor', '批量压缩'],
  batchdownload: ['pms_batchdownload', '批量下载'],
  jsdw: ['pms_jsdw', '结算单位'],
  qsrq: ['pms_qsrq', '起始日期'],
  jzrq: ['pms_jzrq', '截止日期'],
  zhtk: ['pms_zhtk', '总合同款'],
  zsk: ['pms_zsk', '总收款'],
  ykp: ['pms_ykp', '已开票'],
  wsk: ['pms_wsk', '未收款'],
  zfk: ['pms_zfk', '总付款'],
  ysp: ['pms_ysp', '已收票'],
  wfk: ['pms_wfk', '未付款'],
  deletewarning: ['pms_deletewarning', '文档类别或根节点不允许删除'],
  qrscwd: ['pms_qrscwd', '确认删除文档'],
  qrscml: ['pms_qrscml', '确认删除目录'],
  cancel: ['pms_cancel', '取消'],
  qxzmbwj: ['pms_qxzmbwj', '请选择模板文件'],

  jxjfzd: ['pms_jxjfzd', '将文件复制到'],
  jwjydd: ['pms_jwjydd', '将文件移动到'],
  dqczy: ['pms_dqczy', '当前操作员'],
  jwdfsg: ['pms_jwdfsg', '将文档发送给'],
  gxbbh: ['pms_gxbbh', '更新版本号'],
  zjbc: ['pms_zjbc', '直接保存'],
  xgbt: ['pms_xgbt', '修改标题'],
  dirname: ['pms_dirname', '目录名'],
  wbs: ['pms_wbs', 'WBS'],
  wbslcb: ['pms_wbslcb', 'WBS里程碑'],
  bz: ['pms_bz', '备注'],
  skdh: ['pms_skdh', '收款单号'],
  skrq: ['pms_skrq', '收款日期'],
  jsjh: ['pms_jsjh', '结算计划'],
  skje: ['pms_skje', '收款金额'],
  kprq: ['pms_kprq', '发票日期'],
  fkdh: ['pms_fkdh', '付款单据号'],
  fkrq: ['pms_fkrq', '付款日期'],
  fkje: ['pms_fkje', '付款金额'],
  fph: ['pms_fph', '发票号'],
  nsrsbh: ['pms_nsrsbh', '纳税人识别号'],
  name: ['pms_name', '名称'],
  fpje: ['pms_fpje', '发票金额'],
  view: ['pms_view', '查看'],
  editbj: ['pms_editbj', '编辑'],
  lsbb: ['pms_lsbb', '历史版本'],
  yyls: ['pms_yyls', '用印历史'],
  newbtn: ['pms_newbtn', '新增'],
  bgbtn: ['pms_bgbtn', '变更'],
  bgtitle: ['pms_bgtitle', '项目信息变更-新增'],
  htnewtitle: ['pms_htnewtitle', '合同信息-新增'],
  contractlist: ['pms_contractlist', '合同列表'],
  WBS: ['pms_wbs', 'WBS'],
  bhyj: ['pms_bhyj', '驳回意见'],
  bhyjplaceholder: [
    'pms_bhyjplaceholder',
    '描述文字的字数最大不能超过50，并且单行最右侧尽量不要是标点符号',
  ],
  wsbtx: ['pms_wsbtx', '有日志未上报，是否返回我的日志进行上报'],
  yes: ['pms_yes', '是'],
  no: ['pms_no', '否'],
  fj: ['pms_fj', '附件'],
  approvespr: ['pms_approvespr', '审批人'],
  approvespsj: ['pms_approvespsj', '审批时间'],
  approveshr: ['pms_approveshr', '审核人'],
  approveshsj: ['pms_approveshsj', '审核时间'],
  approvezt: ['pms_approvezt', '状态'],
  approvesp: ['pms_approvesp', '送审'],
  approvesqqs: ['pms_approvesqqs', '申请去审'],
  approvesh: ['pms_approvesh', '审核'],
  approveqsh: ['pms_approveqsh', '去审核'],
  approvespzz: ['pms_approvespzz', '送审追踪'],

  docplsc: ['pms_docplsc', '批量上传'],
  sharetowiki: ['pms_sharetowiki', '分享到知识'],
  achivefile: ['pms_achivefile', '归档'],
  cancelachivefile: ['pms_cancelachivefile', '取消归档'],

  businessbillno: ['pms_businessbillno', '业务点单据号'],
};
let langType;

if (window.Proxy) {
  langType = new window.Proxy(targetConfig, {
    get(target, p) {
      const val = target[p] || [];
      return PmsLang[val[0]] || val[1] || p;
    },
  });
} else {
  Object.keys(targetConfig).forEach((key) => {
    const val = targetConfig[key] || [];
    Object.defineProperty(targetConfig, key, {
      get: function () {
        return PmsLang[val[0]] || val[1] || key;
      },
    });
  });
  langType = targetConfig;
}

export default langType;
